name = "IsacRegistry"
uuid = "d6d2a3e8-6288-4854-becd-c6e9d7c22d8e"
repo = "https://github.com/isaccnrbo/IsacRegistry.git"
description = "private IsacRegistry"

[packages]
82dd0fe1-4e75-413c-9a72-18f382ba1d2e = { name = "IsacFileReader", path = "I/IsacFileReader" }
9e7f6a50-18ad-4244-91e0-d4fb5b087add = { name = "GeoUtils", path = "G/GeoUtils" }
a2b3d639-5716-4ad9-b4c6-7c6b6078917d = { name = "IsacBinaryReader", path = "I/IsacBinaryReader" }
