name = "IsacRegistry"
uuid = "d6d2a3e8-6288-4854-becd-c6e9d7c22d8e"
repo = "https://github.com/isaccnrbo/IsacRegistry.git"
description = "private IsacRegistry"

[packages]
a2b3d639-5716-4ad9-b4c6-7c6b6078917d = { name = "IsacBinaryReader", path = "I/IsacBinaryReader" }
